DROP DATABASE IF EXISTS tarot_db;
CREATE DATABASE tarot_db;
USE tarot_db;
CREATE TABLE suits (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
suit_name VARCHAR(30) UNIQUE NOT NULL
);
CREATE TABLE cups(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
card_name VARCHAR(30) UNIQUE NOT NULL,
upright VARCHAR(100) UNIQUE NOT NULL,
reversed VARCHAR(100) UNIQUE NOT NULL
);

